// ROUTES
export const ROUTES = {
    MAIN_PAGE: '/quiz',
};

// GENDERS
export const GENDERS = {
    MALE: 'male',
    FEMALE: 'female',
    OTHER: 'other',
};

// CONTEXT ACTIONS
export const MAIN_CONTEXT_ACTIONS = {
    SET_PLAYERS: 'SET_PLAYERS',
    SET_PLAYER: 'SET_PLAYER',
    SET_QUESTION: 'SET_QUESTION',
    START_COUNTDOWN: 'START_COUNTDOWN',
    STOP_COUNTDOWN: 'STOP_COUNTDOWN',
    RESET_TIMER: 'RESET_TIMER',
    SET_QUESTION_ANSWERED: 'SET_QUESTION_ANSWERED',
    RESET_QUESTION: 'RESET_QUESTION',
    SET_QUESTIONS: 'SET_QUESTIONS',
};

// TIME FORMATS
export const FORMATS = {
    MINUTES: 'MINUTES',
    SECONDS: 'SECONDS',
};

// QUESTIONS DIFFICULTY
export const QUESTIONS = {
    EASY: 'EASY',
    MEDIUM: 'MEDIUM',
    HARD: 'HARD',
};

// BUTTON VARIANTS
export const BUTTON_VARIANT = {
    PINK: 'pink',
    BLUE: 'blue',
    PURPLE: 'purple',
};

// BUTTON SIZES
export const BUTTON_SIZE = {
    SMALL: 'small',
};
