const easyQuestions = [
    {
        id: 1,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 2,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 3,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 4,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 5,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 6,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 7,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 8,
        difficulty: 'easy',
        answerPoints: 100,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
];

const mediumQuestions = [
    {
        id: 9,
        difficulty: 'medium',
        answerPoints: 250,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 10,
        difficulty: 'medium',
        answerPoints: 250,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 11,
        difficulty: 'medium',
        answerPoints: 250,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 12,
        difficulty: 'medium',
        answerPoints: 250,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
];

const hardQuestions = [
    {
        id: 13,
        difficulty: 'hard',
        answerPoints: 500,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 14,
        difficulty: 'hard',
        answerPoints: 500,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 15,
        difficulty: 'hard',
        answerPoints: 500,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
    {
        id: 16,
        difficulty: 'hard',
        answerPoints: 500,
        question: 'Что такое "Предпринимательское право"?',
        answer: 'Это слишком сложный вопрос, я не знаю ответа ;(',
        answered: false,
    },
];

export const questions = { easyQuestions, mediumQuestions, hardQuestions };
